
# DATABASE
DB_HOST = "161.35.60.197"
DB_SERVICE = "tcs7"
DB_USER = "modulo4"
DB_PASSWORD = "modulo4"

# SEARCH
WS_PORTAL_LABORAL = "linkedin"
WS_PORTAL_LABORAL_URL = "https://www.linkedin.com"
WS_PAGINAS = 2  # 500 CANTIDAD DE PAGINAS A SCRAPEAR
WS_PAGINA_INICIAL = 1  # NUMERO DE PAGINA DESDE DONDE SE EMPEZARA A SCRAPEAR
WS_OFERTAS = None  # CANTIDAD DE OFERTAS POR PAGINA A SCRAPEAR (None: Sin limite)
WS_AREA = None  # FILTRO DE AREA PARA REALIZAR LA BUSQUEDA (None: Sin filtro)
